module.exports = {
  geocoding: {
    version: "0.2",
    attribution:
      "https://openrouteservice.org/terms-of-service/#attribution-geocode",
    query: {
      text: "Antananariv",
      parser: "pelias",
      parsed_text: { subject: "Antananariv" },
      size: 10,
      layers: [
        "venue",
        "street",
        "country",
        "macroregion",
        "region",
        "county",
        "localadmin",
        "locality",
        "borough",
        "neighbourhood",
        "continent",
        "empire",
        "dependency",
        "macrocounty",
        "macrohood",
        "microhood",
        "disputed",
        "postalcode",
        "ocean",
        "marinearea",
      ],
      private: false,
      lang: {
        name: "French",
        iso6391: "fr",
        iso6393: "fra",
        via: "header",
        defaulted: false,
      },
      querySize: 20,
    },
    warnings: ["performance optimization: excluding 'address' layer"],
    engine: { name: "Pelias", author: "Mapzen", version: "1.0" },
    timestamp: 1669145123037,
  },
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.522391, -18.902964] },
      properties: {
        id: "421181453",
        gid: "whosonfirst:locality:421181453",
        layer: "locality",
        source: "whosonfirst",
        source_id: "421181453",
        name: "Antananarivo",
        accuracy: "centroid",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "Antananarivo, AG, Madagascar",
        addendum: {
          concordances: {
            "gn:id": 1070940,
            "gp:id": 1358594,
            "loc:id": "n79034322",
            "ne:id": 1159150835,
            "qs_pg:id": 492814,
            "wd:id": "Q3915",
            "wk:page": "Antananarivo",
          },
        },
      },
      bbox: [47.471021, -18.95367, 47.57376, -18.840977],
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.50704, -18.99109] },
      properties: {
        id: "7670898",
        gid: "geonames:county:7670898",
        layer: "county",
        source: "geonames",
        source_id: "7670898",
        name: "Antananarivo Atsimondrano",
        accuracy: "centroid",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Atsimondrano",
        county_gid: "whosonfirst:county:421200823",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "Antananarivo Atsimondrano, AG, Madagascar",
        addendum: { geonames: { feature_code: "ADM2" } },
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.62569, -18.90155] },
      properties: {
        id: "11926403",
        gid: "geonames:county:11926403",
        layer: "county",
        source: "geonames",
        source_id: "11926403",
        name: "Antananarivo Avaradrano",
        accuracy: "centroid",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Avaradrano",
        county_gid: "whosonfirst:county:1108801111",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "Antananarivo Avaradrano, AG, Madagascar",
        addendum: { geonames: { feature_code: "ADM2" } },
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.518518, -18.907125] },
      properties: {
        id: "node/5704626389",
        gid: "openstreetmap:venue:node/5704626389",
        layer: "venue",
        source: "openstreetmap",
        source_id: "node/5704626389",
        name: "Musée des Pirates Antananarivo",
        housenumber: "103",
        street: "Làlana Liège",
        postalcode: "101",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "Musée des Pirates Antananarivo, Antananarivo, AG, Madagascar",
        addendum: {
          osm: {
            operator: "PRIORI, 103 rue de Liège, Tsaralalana, Antananarivo",
            opening_hours: "09:00-17:00",
          },
        },
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.423009, -18.968717] },
      properties: {
        id: "way/82205367",
        gid: "openstreetmap:venue:way/82205367",
        layer: "venue",
        source: "openstreetmap",
        source_id: "way/82205367",
        name: "École supérieure Polytechnique Antananarivo",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Atsimondrano",
        county_gid: "whosonfirst:county:421200823",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "École supérieure Polytechnique Antananarivo, AG, Madagascar",
        addendum: { osm: { operator: "Université d'Antananarivo" } },
      },
      bbox: [47.4209473, -18.9727531, 47.4275992, -18.9660695],
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.55167, -18.918629] },
      properties: {
        id: "node/6914835086",
        gid: "openstreetmap:venue:node/6914835086",
        layer: "venue",
        source: "openstreetmap",
        source_id: "node/6914835086",
        name: "Institut et Observatoire de Geophysique Antananarivo",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label:
          "Institut et Observatoire de Geophysique Antananarivo, Antananarivo, AG, Madagascar",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.52251, -18.872801] },
      properties: {
        id: "node/7193916893",
        gid: "openstreetmap:venue:node/7193916893",
        layer: "venue",
        source: "openstreetmap",
        source_id: "node/7193916893",
        name: "Novotel Convention and Spa Antananarivo",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label:
          "Novotel Convention and Spa Antananarivo, Antananarivo, AG, Madagascar",
        addendum: {
          osm: { wheelchair: "yes", operator: "Accor Hotels" },
        },
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.531372, -18.917462] },
      properties: {
        id: "node/806280484",
        gid: "openstreetmap:venue:node/806280484",
        layer: "venue",
        source: "openstreetmap",
        source_id: "node/806280484",
        name: "Bureau Mairie d'Antananarivo Renivohitra",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label:
          "Bureau Mairie d'Antananarivo Renivohitra, Antananarivo, AG, Madagascar",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.524516, -18.890291] },
      properties: {
        id: "way/839749390",
        gid: "openstreetmap:venue:way/839749390",
        layer: "venue",
        source: "openstreetmap",
        source_id: "way/839749390",
        name: "Radisson Blu Hotel, Antananarivo Waterfront",
        accuracy: "point",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Analamanga",
        region_gid: "whosonfirst:region:85673965",
        region_a: "AG",
        county: "Antananarivo Renivohitra",
        county_gid: "whosonfirst:county:1108801113",
        locality: "Antananarivo",
        locality_gid: "whosonfirst:locality:421181453",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label:
          "Radisson Blu Hotel, Antananarivo Waterfront, Antananarivo, AG, Madagascar",
        addendum: { osm: { brand: "Radisson Blu" } },
      },
      bbox: [47.5243159, -18.8905488, 47.5247162, -18.890034],
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [46.822667, -18.970271] },
      properties: {
        id: "85674025",
        gid: "whosonfirst:region:85674025",
        layer: "region",
        source: "whosonfirst",
        source_id: "85674025",
        name: "Itasy",
        accuracy: "centroid",
        country: "Madagascar",
        country_gid: "whosonfirst:country:85632223",
        country_a: "MDG",
        region: "Itasy",
        region_gid: "whosonfirst:region:85674025",
        region_a: "IT",
        continent: "Afrique",
        continent_gid: "whosonfirst:continent:102191573",
        label: "Itasy, Madagascar",
        addendum: {
          concordances: {
            "fips:code": "MA05",
            "gn:id": 7670855,
            "gp:id": 2346150,
            "hasc:id": "MG.AV.IT",
            "qs_pg:id": 362635,
          },
        },
      },
      bbox: [46.166475, -19.428242, 47.467939, -18.6558],
    },
  ],
  bbox: [46.166475, -19.428242, 47.62569, -18.6558],
};
